### ISSUE TITLE
Godlike Multi-objective 

### ISSUE THREAD

**Issue by ambrix** [cengique/FEX-GODLIKE#1] opened 2015-06-20 10:22 UTC
[Simulated Annealing] Ok for Single-Objective. No work for Multi-obective. I attach the files. Thanks

![buck_of_img](https://cloud.githubusercontent.com/assets/12895901/8266892/fc9c02ac-1746-11e5-9d78-478399a44f19.png)
![opt_sa_buck](https://cloud.githubusercontent.com/assets/12895901/8266893/fc9eb1aa-1746-11e5-941f-df711c4e3236.png)

**Comment by cengique** [comment] 2015-06-21 11:31
@ambrix : thanks for the info. I tested this and it works for me. I think you downloaded the wrong GODLIKE. You need to download it from **this** fork. So go to https://github.com/cengique/FEX-GODLIKE and use the download link to download and install it. You won't get the index error. Next time please paste your code instead of attaching images. It's difficult for me to type and test them.

**Comment by cengique** [comment] 2015-06-25 14:34
Closing this because I can't reproduce it.

**Closed as completed by cengique** 2015-06-25 14:34 UTC

**Comment by josiasritter** [comment] 2016-06-07 19:27
@cengique
You fixed the bugs concerning single functions that return multiple objectives. Great work!
I had the same problem as @ambrix , but after downloading your GODLIKE version it finally works.
Thanks a lot!

**Comment by cengique** [comment] 2016-06-07 20:30
Glad it was useful, @josiasritter! I also made some other changes after the release, so make sure you download the latest ZIP.
